spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manageservers
    username: maniraj
    password: Alliswell@1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show_sql: true
